### ISSUE TITLE
Plugin fails with 'Tag' object has no attribute 'gramps_id'

### ISSUE THREAD

**Issue by fordprefect480** [DavidMStraub/gramps-addon-webapisync#6]
I started with a Gramps Web droplet and created 2 people and a few events directly in there. Then I installed the Gramps desktop app and created one person. Then I installed the api sync plugin:
* Open the plugin
* Enter credentials, click Next.
* Plugin says "Fetching remote data..."
* Plugin says "Comparing local and remote data..."
* Then error dialog opens:
![image](https://user-images.githubusercontent.com/1783639/192652039-ee54a6b1-1260-4556-b093-e75bba6c43ea.png)

```
727145: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\owens\AppData\Roaming\gramps\gramps51\plugins\gramps-addon-webapisync-main\webapisync.py", line 206, in prepare
    self.confirmation.prepare(self.actions)
  File "C:\Users\owens\AppData\Roaming\gramps\gramps51\plugins\gramps-addon-webapisync-main\webapisync.py", line 719, in prepare
    gid = obj1.gramps_id
AttributeError: 'Tag' object has no attribute 'gramps_id'
```

Gramps info:
```
GRAMPS: AIO64-5.1.5-1 
Python: 3.6.4 (default, Jan 23 2018, 13:17:37)  ... 
BSDDB: 6.1.0 (6, 0, 30) 
sqlite: 3.21.0 (2.6.0)
LANG: en_GB.UTF-8
OS: Windows
```

Downloaded plugin as at commit `1c067f7`.

**Comment by DavidMStraub** [comment]
The current version in this repository should fix the issue!
